
/**
 * La clase Enum Pieza contiene todas las piezas en las que se descomponen los muebles
 * 
 * @Ana Belén
 * @version 1
 */
public enum Pieza
{
    TABLON40, TABLON90, TABLON120, CRISTAL, PATAALTA, PATABAJA, PATAMESITA, PATACOCINA, PATASPLEGABLE, PATASESCRITORIO, ASIENTOCOCINA,
    ASIENTOESCRITORIO, ASIENTOPLEGABLE, RESPALDOCOCINA, RESPALDOESCRITORIO, RESPALDOPLEGABLE, TORNILLO, RUEDA
}
